server:
  port: 9091

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: rating-service
  datasource:
    url: jdbc:mysql://ibmhackajobdb.cygwibizailj.ap-southeast-1.rds.amazonaws.com:3306/hackajobsquad1?useSSL=false
    username: ibmhackajob
    password: Welcome123
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none